name: Python application test with Github Actions

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        make install
        make post-install
    - name: Lint with pylint
      run: |
        make lint
    - name: Test with pytest
      run: |
        make test
    - name: Format code
      run: |
        make format
    - name: Build container
      run: |
        make build
    - name: Log in to Docker Hub
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_ACCESS_TOKEN }}
    - name: Tag Docker image
      run: docker tag deploy-fastapi "${{ secrets.DOCKER_USERNAME }}/deploy-fastapi:latest"
    - name: Push Docker image to Docker Hub
      run: docker push "${{ secrets.DOCKER_USERNAME }}/deploy-fastapi:latest"

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: SSH into VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          port: ${{ secrets.VPS_PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo docker pull aminasa/deploy-fastapi:latest
            sudo docker stop aminasa/deploy-fastapi || true
            sudo docker rm aminasa/deploy-fastapi || true
            sudo docker run -d -p 127.0.0.1:9000:8080 --name deploy-fastapi aminasa/deploy-fastapi:latest
